# Q - 1 )Below are nested “K” for loops (3 marks)
n= int(input("Enter the limit"))

for i in range(n):
    for j in range(n):
        for l in range(n):
            #…
                #…
                    #…
                        #K for loops in total:
                            #…
                                #…
                                    #…
                                        for z in range(n):
                                            print("Time complexity")

#Time Complexity:-O(N^K)